services:
  log-analytics-status:
    build: .
    image: distributed-log-analytics:latest
    ports:
      - "8080:8080"
    environment:
      PROJECT_ID: distributed-log-analytics
      REGION: us-central1
      RAW_BUCKET: distributed-log-analytics-raw-logs
      OUTPUT_BUCKET: distributed-log-analytics-spark-output
      BQ_DATASET: logs_dataset
      LOOKER_STUDIO_URL: https://lookerstudio.google.com
      DATASET_LOCAL_PATH: dataset/HDFS_full/HDFS.log
      DATASET_GCS_PATH: gs://distributed-log-analytics-raw-logs/loghub/hdfs/full/HDFS.log
    volumes:
      - .:/app
